### ISSUE TITLE
关于改进echo模式的压测逻辑的建议

### ISSUE THREAD

**Issue by buexplain** [lxzan/wsbench#3]
现在的echo模式压测，相同参数下，每次测试的结果，浮动比较大。
具体请看下面的数据：
```bash
4:07PM INF Duration=8.9868487s IOPS=11127 P50=2605ms P90=4930ms P99=6451ms
4:07PM INF Duration=9.5169201s IOPS=10507 P50=2020ms P90=3753ms P99=5262ms
4:07PM INF Duration=9.2686362s IOPS=10789 P50=2769ms P90=5058ms P99=6613ms
4:10PM INF Duration=9.0430895s IOPS=11058 P50=2310ms P90=3342ms P99=4190ms
```
这种情况下，我尝试过调整参数，我想得到一个：连接数量、消息数量都比较大，但是P99又比较理想的IOPS值。
这种IOPS值比较有参考价值。但是目前的压测逻辑做不到，当然不排除我使用姿势不对的可能。
我建议改动一下压测逻辑：
1. 通过参数numMessage设置一个总消息量
2. 每个连接都去抢发送消息的资格，抢到就发送，达到总消息量就退出
3. 每个连接必须等待上一次发送的消息回来后才能再次抢下一个发送的资格

我按上面的逻辑改了一版后，相同的消息总量下，压测数据如下：
```bash
3:51PM INF Duration=11.076374s IOPS=9030 P50=132ms P90=379ms P99=520ms
3:51PM INF Duration=10.7231663s IOPS=9325 P50=135ms P90=334ms P99=551ms
3:51PM INF Duration=10.7231663s IOPS=9325 P50=135ms P90=334ms P99=551ms
4:04PM INF Duration=11.2103891s IOPS=8920 P50=120ms P90=432ms P99=628ms
```

**Comment by lxzan** [comment]
可以啊, 来一个PR 

我以前也试过, 改成"一收一发"的模式后测试结果确实会稳定许多

**Comment by lxzan** [comment]
我在你的基础上做了一些修改, 改成了默认8并发度, 1并发度对服务端压力太小了.

<img width="1402" alt="image" src="https://github.com/lxzan/wsbench/assets/17956540/c1806652-8586-472e-86bf-e60ba77c1b6a">

明天再打tag吧, 先用这个命令安装:
```bash
go install github.com/lxzan/wsbench@67ffb656d9d4c17d078f5cdbb86da6b662937935
```

**Comment by buexplain** [comment]
dev分支的代码是不是漏掉了一行：
```go
p := message.Bytes()[size-8:]
```
我执行后报错如下：
```go
C:\Users\Administrator\Desktop>wsbench echo -c 2000 -n 100000  -f ./test.txt -u ws://192.168.241.2:6060/netsvr
panic: runtime error: index out of range [7] with length 5

goroutine 8068 [running]:
encoding/binary.littleEndian.Uint64(...)
        D:/Go/src/encoding/binary/binary.go:102
github.com/lxzan/wsbench/pkg/echo.(*Handler).OnMessage(0xc00001f2f0, 0xc003f4ffd0?, 0xc0000911a0)
        C:/Users/Administrator/go/pkg/mod/github.com/lxzan/wsbench@v1.0.11-0.20230911125156-67ffb656d9d4/pkg/echo/echo.go:227 +0x1ff
github.com/lxzan/gws.(*Conn).emitMessage.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/lxzan/gws@v1.6.10/reader.go:156 +0x27
github.com/lxzan/gws.channel.Go.func1()
        C:/Users/Administrator/go/pkg/mod/github.com/lxzan/gws@v1.6.10/task.go:81 +0x23
created by github.com/lxzan/gws.channel.Go in goroutine 4570
        C:/Users/Administrator/go/pkg/mod/github.com/lxzan/gws@v1.6.10/task.go:80 +0x73
```

**Comment by lxzan** [comment]
已经修复了

```bash
go install github.com/lxzan/wsbench@6bba9a005855b8d2641fd5b308a8f525ee4f7280
```

**Comment by buexplain** [comment]
是onMessage的时候计算时间戳，需要截取消息的尾部的时间戳。
现在的代码是这样子的
```go
cost := (uint64(time.Now().UnixNano()) - binary.BigEndian.Uint64(message.Bytes())) / 1000000
```
原来是这样子的
```go
size := message.Data.Len()
p := message.Bytes()[size-8:]
cost := (uint64(time.Now().UnixNano()) - binary.LittleEndian.Uint64(p)) / 1000000
```

**Comment by lxzan** [comment]
> 是onMessage的时候计算时间戳，需要截取消息的尾部的时间戳。 现在的代码是这样子的
> 
> ```go
> cost := (uint64(time.Now().UnixNano()) - binary.BigEndian.Uint64(message.Bytes())) / 1000000
> ```
> 
> 原来是这样子的
> 
> ```go
> size := message.Data.Len()
> p := message.Bytes()[size-8:]
> cost := (uint64(time.Now().UnixNano()) - binary.LittleEndian.Uint64(p)) / 1000000
> ```

稍微改了下, 效果是一样的. 

cost上面一行有个Next, 之后调用Bytes()就是取尾部的8byte了, 你可以断点看看

**Comment by lxzan** [comment]
压测结果稳定下来了吧 😅

并发度是可以调的
```bash
 wsbench echo -c 1000 -n 100000 -p 1000 -u ws://127.0.0.1:8000/connect --concurrency=4
```

**Comment by buexplain** [comment]
连跑四次，结果相近，nice。
```bash
wsbench echo -c 1000 -n 100000  -f C:/Users/Administrator/Desktop/test.txt -u ws://192.168.241.2:7272 --concurrency=4
11:30AM INF Percentage=20.31% Requests=20307
11:30AM INF Percentage=40.83% Requests=40828
11:30AM INF Percentage=62.68% Requests=62678
11:30AM INF Percentage=85.25% Requests=85249
11:30AM INF Percentage=99.98% Requests=99979
11:30AM INF Percentage=100.00% Requests=100000
11:30AM INF Duration=5.444381s IOPS=18367 P50=113ms P90=418ms P99=1004ms

wsbench echo -c 1000 -n 100000  -f C:/Users/Administrator/Desktop/test.txt -u ws://192.168.241.2:7272 --concurrency=4
11:30AM INF Percentage=20.84% Requests=20845
11:30AM INF Percentage=42.22% Requests=42218
11:30AM INF Percentage=63.34% Requests=63341
11:30AM INF Percentage=85.23% Requests=85230
11:30AM INF Percentage=99.99% Requests=99991
11:30AM INF Percentage=100.00% Requests=100000
11:30AM INF Duration=6.0442003s IOPS=16544 P50=106ms P90=437ms P99=950ms

wsbench echo -c 1000 -n 100000  -f C:/Users/Administrator/Desktop/test.txt -u ws://192.168.241.2:7272 --concurrency=4
11:30AM INF Percentage=20.41% Requests=20405
11:30AM INF Percentage=43.02% Requests=43020
11:30AM INF Percentage=65.52% Requests=65518
11:30AM INF Percentage=87.61% Requests=87607
11:30AM INF Percentage=99.96% Requests=99958
11:30AM INF Percentage=100.00% Requests=100000
11:30AM INF Duration=5.3034214s IOPS=18855 P50=111ms P90=425ms P99=866ms

wsbench echo -c 1000 -n 100000  -f C:/Users/Administrator/Desktop/test.txt -u ws://192.168.241.2:7272 --concurrency=4
11:30AM INF Percentage=23.58% Requests=23581
11:30AM INF Percentage=45.17% Requests=45175
11:30AM INF Percentage=65.80% Requests=65796
11:30AM INF Percentage=85.87% Requests=85868
11:30AM INF Percentage=99.97% Requests=99970
11:30AM INF Percentage=99.98% Requests=99984
11:30AM INF Percentage=100.00% Requests=100000
11:30AM INF Duration=6.2805319s IOPS=15922 P50=113ms P90=421ms P99=913ms
```
